services:

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=supersecretkey


  db:
    image: mariadb:10.6-focal
    
    container_name: db

    restart: always

    environment:
      - MARIADB_ROOT_PASSWORD=1234
    
    volumes:
      - ./bdd:/var/lib/mysql
    

  #frontend:
  #  build: ./frontend
  #  ports:
  #    - "8080:80"
  #  container_name: frontend